#dbPath: ""
#syslogUDPPort: 514
#syslogTCPPort: 6514
#netflowPort: 2055
#snmpTrapPort: 162
#otelHTTPPort: 4318
#otelgRPCPort: 4317
otelRetention: 720
otelFrom: ""
otelCert: ""
otelgKey: ""
otelCA: ""
#mqttTCPPort: 1883
#mqttWDPort: 1884
mqttUsers: ""
mqttFrom: ""
mqttCert: ""
mqttgKey: ""
#winEventLogChannel: "System,Security,Application"
winEventLogCheckInterval: 60
winEventLogCheckStart: 0
winRemote: ""
winUser: ""
winPassword: ""
winAuth: ""
#winLogSJIS: false
#syslogDst: []
#trapDst: []
#webhookDst: []
#mqttDst: []
trapCommunity: "public"
logRetention: 720
notifyRetention: 30
reportRetention: 30
reportInterval: 60
reportTopN: 10
anomalyReportThreshold: 0.01
anomalyUseTimeData: true
anomalyNotifyDelay: 30
grockPat: []
grokDef: ""
namedCaptures: ""
keyValParse: false
resolveHostName: false
geoIPDB: ""
#sigmaRules: "/datastore/sigma/rules"
#sigmaConfigs: "/datastore/sigma/config"
#sigmaRules: embed:test/syslog
#sigmaConfig: embed:windows
sigmaSkipError: false
#mibPath: "/datastore/mibs"
mcpEndpoint: ""
mcpFrom: ""
mcpToken: ""
debug: false
